mejorado el script funciones

diff --git a/4.0/Funciones/funciones_updater b/4.0/Funciones/funciones_updater
--- a/4.0/Funciones/funciones_updater
+++ b/4.0/Funciones/funciones_updater
@@ -2,15 +2,16 @@
 
 # Script by www.seguridadwireless.net
 
-FUNCIONES_VERSION=20260310
+FUNCIONES_VERSION=20260711
+
 # Colores
-CIERRE=${CIERRE:-"[0m"}
-ROJO=${ROJO:-"[1;31m"}
-VERDE=${VERDE:-"[1;32m"}
-CYAN=${CYAN:-"[1;36m"}
-AMARILLO=${AMARILLO:-"[1;33m"}
-BLANCO=${BLANCO:-"[1;37m"}
-ROSA=${ROSA:-"[1;35m"}
+CIERRE=$(tput init)
+ROJO=$(tput setaf 9)
+VERDE=$(tput setaf 10)
+CYAN=$(tput setaf 14)
+AMARILLO=$(tput setaf 11)
+BLANCO=$(tput setaf 15)
+ROSA=$(tput setaf 13)
 
 # Variables globales
 PRGNAM=funciones
@@ -45,22 +46,22 @@ f_exitmode() {
 # Funcion que muestra Presentacion
 f_presentacion() {
 clear
-	sleep 0.1 | echo ""
-	sleep 0.1 | echo ""
-	sleep 0.1 | echo "$BLANCO"  "       ******************************"   
-	sleep 0.1 | echo "$VERDE"   "          Actualizador/Instalador    "   
-	sleep 0.1 | echo "$VERDE"   "          Paquete: "$AMARILLO"$PRGNAM"                                                 
-	sleep 0.1 | echo "$VERDE"   "                                   "
-	sleep 0.1 | echo "$VERDE"   "          www.seguridadwireless.net  "
-	sleep 0.1 | echo "$BLANCO"  "       ******************************"
-	sleep 0.1 | echo "$CERRAR"
+	sleep 0.1 | echo
+	sleep 0.1 | echo
+	sleep 0.1 | echo "${BLANCO}"  "       ******************************"   
+	sleep 0.1 | echo "${VERDE}"   "          Actualizador/Instalador    "   
+	sleep 0.1 | echo "${VERDE}"   "          Paquete: "${AMARILLO}"${PRGNAM}"                                       
+	sleep 0.1 | echo "${VERDE}"   "                                   "
+	sleep 0.1 | echo "${VERDE}"   "          www.seguridadwireless.net  "
+	sleep 0.1 | echo "${BLANCO}"  "       ******************************"
+	sleep 0.1 | echo "${CIERRE}"
 }
 
 # Comprobar conexion by geminis_demon
 f_comprobarConexion() {
    if [ ! "$(ping google.com -c1 2>/dev/null)" ]; then
-      echo "No tengo internet ... el script se cerrara."
-      echo ""
+      echo "${BLANCO}No tengo internet ... el script se cerrara.${CIERRE}"
+      echo
       exit 1
    fi
 }
@@ -71,19 +72,19 @@ f_comprobarUpdates() {
    DIRECTORIO=$(find /opt/wifislax-updaters -type f -name ${PRGNAM}_updater| rev | cut -d/ -f2- | rev)
    SERVIDOR_VERSION=$(timeout -s SIGTERM 10 curl -sk $SERVIDOR_WEB/${DIRECTORIO##*/}/${PRGNAM}_updater | grep "SCRIPT_VERSION=" | head -1 |cut -d "=" -f2)
 
-   echo ${CYAN}Version Script$CIERRE: $ROJO${SCRIPT_VERSION:6}$BLANCO/$AMARILLO${SCRIPT_VERSION:4:2}$BLANCO/$ROJO${SCRIPT_VERSION:0:4}$CIERRE
+   echo ${CYAN}Version Script${CIERRE}: ${ROJO}${SCRIPT_VERSION:6}${BLANCO}/${AMARILLO}${SCRIPT_VERSION:4:2}${BLANCO}/${ROJO}${SCRIPT_VERSION:0:4}${CIERRE}
 
    if [ "$(ping github.com -c1 2>/dev/null)" ]; then
       if [[ $SCRIPT_VERSION -lt $SERVIDOR_VERSION ]]; then
          echo
-         echo "$ROSA"Comprobando si hay actualizaciones para el script..."$CIERRE."
-         echo ${ROJO}NUEVA VERSION$CIERRE
+         echo "${ROSA}"Comprobando si hay actualizaciones para el script..."${CIERRE}."
+         echo ${ROJO}NUEVA VERSION${CIERRE}
          echo
-         echo ${ROSA}Version Server$CIERRE: $ROJO${SERVIDOR_VERSION:6}$BLANCO/$AMARILLO${SERVIDOR_VERSION:4:2}$BLANCO/$ROJO${SERVIDOR_VERSION:0:4}$CIERRE
+         echo ${ROSA}Version Server${CIERRE}: ${ROJO}${SERVIDOR_VERSION:6}${BLANCO}/${AMARILLO}${SERVIDOR_VERSION:4:2}${BLANCO}/${ROJO}${SERVIDOR_VERSION:0:4}${CIERRE}
          echo
          echo ${CYAN}Actualizando ${PRGNAM}_updater
          curl -sk $SERVIDOR_WEB/${DIRECTORIO##*/}/${PRGNAM}_updater -o $DIRECTORIO/${PRGNAM}_updater
-         echo ${ROJO}LISTO$CIERRE
+         echo ${ROJO}LISTO${CIERRE}
          $0
          exit
       fi
@@ -125,22 +126,22 @@ f_versionInstalada() {
    else
    VERSIONLOCAL=$PRGNAM-$INSTALADA
    fi
-   echo ""
-   echo ""$AMARILLO"La version del sistema es..."$CYAN"$VERSIONLOCAL"$CIERRE""
-   echo ""
+   echo
+   echo ""${AMARILLO}"La version del sistema es..."${CYAN}"$VERSIONLOCAL"${CIERRE}""
+   echo
    echo "__________________________________________"
-   echo ""
-   echo ""$AMARILLO"La version mas nueva en su pagina web es..."$CYAN"$PRGNAM-$VERSION"$CIERRE""
-   echo ""
+   echo
+   echo ""${AMARILLO}"La version mas nueva en su pagina web es..."${CYAN}"$PRGNAM-$VERSION"${CIERRE}""
+   echo
    if [ $PRGNAM = x265 ]; then
       echo "${ROJO}ADVERTENCIA:"
       echo "${BLANCO}Actualizar este paquete puede romper ${AMARILLO}ffmpeg"
       echo "${BLANCO}Es posible que necesites recompilar ${AMARILLO}ffmpeg"
       echo
    fi
-   echo ""$BLANCO"Pulsa $ROJO"ENTER" $BLANCO"si deseas actualizarla""
+   echo ""${BLANCO}"Pulsa ${ROJO}"ENTER" ${BLANCO}"si deseas actualizarla""
    read junk
-   echo ""
+   echo
 
 # Si el paquete esta instalado y es el mismo se sube el numero de build
 if [ "$INSTALADA" = $VERSION ]; then
@@ -153,40 +154,40 @@ COMIENZO=$(date +%s)
 }
 
 f_dependencias(){
-echo "$ROSA"Comprobando dependencias ..."$CIERRE"
-echo ""
+echo "${ROSA}"Comprobando dependencias ..."${CIERRE}"
+echo
 for D in $DEPENDENCIAS; do
-BUSCAR=$(echo "$(ls /var/lib/pkgtools/packages|rev|cut -d '-' -f4-|rev|grep -x $D)")
+BUSCAR=$(echo -e "$(ls /var/lib/pkgtools/packages|rev|cut -d '-' -f4-|rev|grep -x $D)")
 if [ -z "$BUSCAR" ]; then
 echo "${BLANCO}Dependencia ${AMARILLO}${D} ${ROJO}NO INSTALADA${BLANCO} ...resolviendo${CIERRE}."
-UPDATER=$(echo "$(find /opt/wifislax-updaters/* -name ${D}_updater)")
+UPDATER=$(echo -e "$(find /opt/wifislax-updaters/* -name ${D}_updater)")
 if [ -z "$UPDATER" ]; then
 if [ "$(ping www.slackbuilds.org -c1 2>/dev/null)" ]; then
 slapt-src -u &>/dev/null
 else
-echo ${ROJO}
-echo "Parece que slackbuilds.org no responde ... intentalo mas tarde"
-echo ${CIERRE}
+echo
+echo "${ROJO}Parece que slackbuilds.org no responde ... intentalo mas tarde${CIERRE}"
+echo
 exit 1
 fi
 if [ ${D} = pylast ]; then
-xterm -e sh -c "TAG=slackbuilds PYTHON3=no slapt-src -y -i ${D}"
+xterm -e sh -c "TAG=slackbuilds PYTHON3=no slapt-src -y -n -i ${D}"
 else
-xterm -e sh -c "TAG=slackbuilds slapt-src -y -i ${D}"
+xterm -e sh -c "TAG=slackbuilds slapt-src -y -n -i ${D}"
 fi
-PACKDIR=$(echo $(find /usr/src/slapt-src/ -name "${D}-*.txz"))
-XZMPACK=$(echo $(find /usr/src/slapt-src/ -name "${D}-*.txz"|rev|cut -d / -f-1|rev|sed 's/.txz/.xzm/g'))
-GROUP=$(echo $(find /usr/src/slapt-src/ -name "${D}-*.txz"|rev|cut -d / -f3|rev))
+PACKDIR=$(echo -e $(find /usr/src/slapt-src/ -name "${D}-*.txz"))
+XZMPACK=$(echo -e $(find /usr/src/slapt-src/ -name "${D}-*.txz"|rev|cut -d / -f-1|rev|sed 's/.txz/.xzm/g'))
+GROUP=$(echo -e $(find /usr/src/slapt-src/ -name "${D}-*.txz"|rev|cut -d / -f3|rev))
 if [ ! "${PACKAGETYPE}" = disable ]; then
 if [ ! -d ${HOME}/$ESCRITORIO/${PRGNAM}_depends/$GROUP ]; then
 mkdir -p ${HOME}/$ESCRITORIO/${PRGNAM}_depends/$GROUP
 fi
 fi
-VERIFICAR=$(echo "$(ls /var/lib/pkgtools/packages|rev|cut -d '-' -f4-|rev|grep -x $D)")
+VERIFICAR=$(echo -e "$(ls /var/lib/pkgtools/packages|rev|cut -d '-' -f4-|rev|grep -x $D)")
 if [ -z "$VERIFICAR" ]; then
-echo ""
+echo
 echo "${ROJO}No se puedo resolver la dependencia ${AMARILLO}${D}${CIERRE}."
-echo ""
+echo
 exit 1
 else
 if [ "${PACKAGETYPE}" = txz ]; then
@@ -203,9 +204,9 @@ else
 xterm -e sh -c "yes y | $UPDATER"
 VERIFICAR=`echo "$(ls /var/lib/pkgtools/packages|rev|cut -d '-' -f4-|rev|grep -x $D)"`
 if [ -z "$VERIFICAR" ]; then
-echo ""
+echo
 echo "${ROJO}No se puedo resolver la dependencia ${AMARILLO}${D}${CIERRE}."
-echo ""
+echo
 exit 1
 else
 echo "${BLANCO}Dependencia ${AMARILLO}${D} ${CYAN}RESUELTA${CIERRE}."
@@ -225,8 +226,8 @@ f_elimina() {
    fi
    fi
 
-   echo ""
-   echo "$ROJO"Eliminando la version del sistema..."$CIERRE"
+   echo
+   echo "${ROJO}"Eliminando la version del sistema..."${CIERRE}"
    removepkg $(ls /var/lib/pkgtools/packages|rev|cut -d'-' -f3-|sed 's/-/ /'|rev|grep "^$PRGNAM "|cut -d' ' -f1)
 }
 
@@ -260,8 +261,8 @@ ARGS=clone
 fi
 
 if [ ! -f $SOURCES ]; then
-echo 
-echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
+echo  
+echo "${CYAN}"Descargando sources de $PRGNAM-$VERSION"${CIERRE}"
 echo "${ROSA}"
 $GESTOR $ARGS $DOWNLOAD
 echo "${CIERRE}"
@@ -271,7 +272,7 @@ fi
 #Preparamos entorno
 f_descomprimir(){
 	echo
-	echo "$VERDE"Descomprimiendo ..."$CIERRE"
+	echo "${VERDE}"Descomprimiendo ..."${CIERRE}"
 	echo
 	sleep 1
 	rm -rf $PRGNAM-$VERSION
@@ -288,7 +289,7 @@ f_cd(){
 	echo "${ROJO}La funcion CD no existe o esta vacia.${CIERRE}"
 	echo
 	fi
-	cd $TMP/$CD||echo "${ROJO}Error en funcion CD.${CIERRE}"
+	cd $TMP/$CD||echo -e "${ROJO}Error en funcion CD.${CIERRE}"
 	chown -R root:root .
 	find -L . \
 	\( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
@@ -300,7 +301,7 @@ f_cd(){
 f_categoria(){
    # Guardamos los modulos en carpetas por categoria
    cd ..
-   CATEGORIA=$(echo "$(find /opt/wifislax-updaters/* -name ${PRGNAM}_updater| cut -d "/" -f4)")
+   CATEGORIA=$(echo -e "$(find /opt/wifislax-updaters/* -name ${PRGNAM}_updater| cut -d "/" -f4)")
    if [ ! -d $HOME/$ESCRITORIO/$CATEGORIA ]; then
    mkdir -p $HOME/$ESCRITORIO/$CATEGORIA
    fi
@@ -309,8 +310,8 @@ f_categoria(){
 f_xzm(){
    ### Package xzm ###
    if [ $PACKAGETYPE = xzm ]; then
-   echo ""
-   echo "$VERDE"Instalando y creando modulo ${AMARILLO}xzm ..."$CIERRE"
+   echo
+   echo "${VERDE}"Instalando y creando modulo ${AMARILLO}xzm ..."${CIERRE}"
    sleep 1
 
    f_categoria
@@ -325,15 +326,15 @@ f_xzm(){
 f_txz(){
    ### Package txz ###
    if [ $PACKAGETYPE = txz ]; then
-   echo ""
-   echo "$VERDE"Instalando y creando paquete ${AMARILLO}txz ..."$CIERRE"
+   echo
+   echo "${VERDE}"Instalando y creando paquete ${AMARILLO}txz ..."${CIERRE}"
    sleep 1
    
    f_categoria
    
    #Variables de busqueda para slack-desk
    if [ "$(ping www.slackbuilds.org -c1 2>/dev/null)" ]; then
-   BUSQUEDA=$(echo $PRGNAM|rev)
+   BUSQUEDA=$(echo -e $PRGNAM|rev)
    SLACKWEB=https://slackbuilds.org
    SLACKVER=$(curl -s $SLACKWEB/|grep repository/[0-9]|cut -d / -f3)
    SECTION=$(cat /etc/wifislax-updaters/SLACKBUILDS.TXT|grep LOCATION|rev|grep "^$BUSQUEDA/"|cut -d / -f2|rev)
@@ -356,8 +357,8 @@ f_txz(){
 f_disable(){
    ### Package disabled ###
    if [ $PACKAGETYPE = disable ]; then
-   echo ""
-   echo "$VERDE"Instalando ..."$CIERRE"
+   echo
+   echo "${VERDE}"Instalando ..."${CIERRE}"
    sleep 1
    
    #Creamos paquete
@@ -389,7 +390,7 @@ f_tareasFinales() {
    clear
    
    # Actualizar sistema mimetypes schemas etc
-   echo ""$VERDE"Actualizando sistema$BLANCO...$CIERRE"
+   echo ""${VERDE}"Actualizando sistema${BLANCO}...${CIERRE}"
 
    # Comandos de sistema
    cacheupdater
@@ -402,11 +403,11 @@ f_tareasFinales() {
    # Informe final
    clear
    if [ $PACKAGETYPE = disable ]; then
-   echo ""$VERDE"Instalado paquete "$AMARILLO"$PRGNAM-$VERSION"$CIERRE""
-   echo ""
+   echo ""${VERDE}"Instalado paquete "${AMARILLO}"$PRGNAM-$VERSION"${CIERRE}""
+   echo
    else
-   echo ""$VERDE"Instalado y Creado paquete "$AMARILLO"$PRGNAM-$VERSION"$CIERRE""
-   echo ""
+   echo ""${VERDE}"Instalado y Creado paquete "${AMARILLO}"$PRGNAM-$VERSION"${CIERRE}""
+   echo
    fi
    # Variables para calcular tiempo de acabado
    AHORA=$(($(date +%s)-3600));
@@ -414,9 +415,9 @@ f_tareasFinales() {
    
    # Informe de acabado
    echo "${AMARILLO}Tiempo empleado${BLANCO}: $TIEMPO"
-   echo ""
-   echo "$VERDE"Bye Bye"$CIERRE"
-   echo ""
+   echo
+   echo "${VERDE}"Bye Bye"${CIERRE}"
+   echo
    
    # Salimos del script
    rm -Rf $TMP &>/dev/null
