funciones informa de error si no puede hacer cd a la ruta de las $SOURCES

diff --git a/Funciones/funciones_updater b/Funciones/funciones_updater
--- a/Funciones/funciones_updater
+++ b/Funciones/funciones_updater
@@ -2,7 +2,7 @@
 
 # Script by www.seguridadwireless.net
 
-FUNCIONES_VERSION=20170409
+FUNCIONES_VERSION=20170421
 
 # Colores
 CIERRE=${CIERRE:-"[0m"}
@@ -273,7 +273,7 @@ f_preparar(){
 	tar xvf $SOURCES || tar xvf $SRCNAM-$VERSION.$EXTENSION || tar xvf $PRGNAM-src-$VERSION.$EXTENSION
 	fi
 	fi 
-	cd $TMP/$(echo $SOURCES|sed "s/.$EXTENSION//g") 2>/dev/null||cd $TMP/$PRGNAM-$SRCNAM-$VERSION 2>/dev/null
+	cd $TMP/$(echo $SOURCES|sed "s/.$EXTENSION//g") 2>/dev/null||cd $TMP/$PRGNAM-$SRCNAM-$VERSION 2>/dev/null||echo "${ROJO}Error en funcion cd${CIERRE}"
 	fi
 	chown -R root:root .
 	find -L . \
