Nueva funcion CD para acceder a ruta de compilacion

diff --git a/Funciones/funciones_updater b/Funciones/funciones_updater
--- a/Funciones/funciones_updater
+++ b/Funciones/funciones_updater
@@ -2,7 +2,7 @@
 
 # Script by www.seguridadwireless.net
 
-FUNCIONES_VERSION=20170513
+FUNCIONES_VERSION=20170526
 
 # Colores
 CIERRE=${CIERRE:-"[0m"}
@@ -154,22 +154,22 @@ f_dependencias(){
 echo "$ROSA"Comprobando dependencias ..."$CIERRE"
 echo ""
 for D in $DEPENDENCIAS; do
-BUSCAR=`echo "$(ls /var/log/packages|rev|cut -d '-' -f4-|rev|grep -x $D)"`
+BUSCAR=$(echo "$(ls /var/log/packages|rev|cut -d '-' -f4-|rev|grep -x $D)")
 if [ -z "$BUSCAR" ]; then
 echo "${BLANCO}Dependencia ${AMARILLO}${D} ${ROJO}NO INSTALADA${BLANCO} ...resolviendo${CIERRE}."
-UPDATER=`echo "$(find /opt/wifislax-updaters/* -name ${D}_updater)"`
+UPDATER=$(echo "$(find /opt/wifislax-updaters/* -name ${D}_updater)")
 if [ -z "$UPDATER" ]; then
 slapt-src -u &>/dev/null
 xterm -e sh -c "yes y | TAG=slackbuilds slapt-src -i ${D}"
-PACKDIR=`echo $(find /usr/src/slapt-src/ -name "${D}-*.txz")`
-XZMPACK=`echo $(find /usr/src/slapt-src/ -name "${D}-*.txz"|rev|cut -d / -f-1|rev|sed 's/.txz/.xzm/g')`
-GROUP=`echo $(find /usr/src/slapt-src/ -name "${D}-*.txz"|rev|cut -d / -f3|rev)`
+PACKDIR=$(echo $(find /usr/src/slapt-src/ -name "${D}-*.txz"))
+XZMPACK=$(echo $(find /usr/src/slapt-src/ -name "${D}-*.txz"|rev|cut -d / -f-1|rev|sed 's/.txz/.xzm/g'))
+GROUP=$(echo $(find /usr/src/slapt-src/ -name "${D}-*.txz"|rev|cut -d / -f3|rev))
 if [ ! "${PACKAGETYPE}" = disable ]; then
 if [ ! -d ${HOME}/Desktop/${PRGNAM}_depends/$GROUP ]; then
 mkdir -p ${HOME}/Desktop/${PRGNAM}_depends/$GROUP
 fi
 fi
-VERIFICAR=`echo "$(ls /var/log/packages|rev|cut -d '-' -f4-|rev|grep -x $D)"`
+VERIFICAR=$(echo "$(ls /var/log/packages|rev|cut -d '-' -f4-|rev|grep -x $D)")
 if [ -z "$VERIFICAR" ]; then
 echo ""
 echo "${ROJO}No se puedo resolver la dependencia ${AMARILLO}${D}${CIERRE}."
@@ -272,10 +272,13 @@ f_preparar(){
 	if [ $EXTENSION = zip ]; then
 	unzip $SOURCES
 	else
-	tar xvf $SOURCES || tar xvf $SRCNAM-$VERSION.$EXTENSION || tar xvf $PRGNAM-src-$VERSION.$EXTENSION
+	tar xvf $SOURCES||tar xvf $SRCNAM-$VERSION.$EXTENSION||tar xvf $PRGNAM-src-$VERSION.$EXTENSION
 	fi
-	fi 
-	cd $TMP/$(echo $SOURCES|sed "s/.$EXTENSION//g") 2>/dev/null||cd $TMP/$PRGNAM-$SRCNAM-$VERSION 2>/dev/null||cd $TMP/$SRCNAM 2>/dev/null||echo "${ROJO}Error en funcion cd${CIERRE}"
+	fi
+	if [ -z $CD ]; then
+	echo "${ROJO}La funcion CD no existe o esta vacia.${CIERRE}"
+	fi
+	cd $TMP/$CD||echo "${ROJO}Error en funcion CD.${CIERRE}"
 	fi
 	chown -R root:root .
 	find -L . \
@@ -288,7 +291,7 @@ f_preparar(){
 f_categoria(){
    # Guardamos los modulos en carpetas por categoria
    cd ..
-   CATEGORIA=`echo "$(find /opt/wifislax-updaters/* -name ${PRGNAM}_updater| cut -d "/" -f4)"`
+   CATEGORIA=$(echo "$(find /opt/wifislax-updaters/* -name ${PRGNAM}_updater| cut -d "/" -f4)")
    if [ ! -d $HOME/Desktop/$CATEGORIA ]; then
    mkdir -p $HOME/Desktop/$CATEGORIA
    fi
