Colores globales en bash

diff --git a/current/Funciones/funciones_updater b/current/Funciones/funciones_updater
--- a/current/Funciones/funciones_updater
+++ b/current/Funciones/funciones_updater
@@ -1,16 +1,8 @@
-#!/bin/bash
+#!/bin/sh
 
 # Script by www.seguridadwireless.net
 
-FUNCIONES_VERSION=20250301
-# Colores
-CIERRE=${CIERRE:-"[0m"}
-ROJO=${ROJO:-"[1;31m"}
-VERDE=${VERDE:-"[1;32m"}
-CYAN=${CYAN:-"[1;36m"}
-AMARILLO=${AMARILLO:-"[1;33m"}
-BLANCO=${BLANCO:-"[1;37m"}
-ROSA=${ROSA:-"[1;35m"}
+FUNCIONES_VERSION=20250406
 
 # Variables globales
 PRGNAM=funciones
@@ -45,22 +37,16 @@ f_exitmode() {
 # Funcion que muestra Presentacion
 f_presentacion() {
 clear
-	sleep 0.1 | echo ""
-	sleep 0.1 | echo ""
-	sleep 0.1 | echo "$BLANCO"  "       ******************************"   
-	sleep 0.1 | echo "$VERDE"   "          Actualizador/Instalador    "   
-	sleep 0.1 | echo "$VERDE"   "          Paquete: "$AMARILLO"$PRGNAM"                                                 
-	sleep 0.1 | echo "$VERDE"   "                                   "
-	sleep 0.1 | echo "$VERDE"   "          www.seguridadwireless.net  "
-	sleep 0.1 | echo "$BLANCO"  "       ******************************"
-	sleep 0.1 | echo "$CERRAR"
+   sleep 0.1 | echo -e "${BLANCO}\n\n         ******************************"   
+   sleep 0.1 | echo -e "${VERDE}            Actualizador/Instalador \n            Paquete:${AMARILLO} $PRGNAM\n"                         
+   sleep 0.1 | echo -e "${VERDE}            www.seguridadwireless.net"
+   sleep 0.1 | echo -e "${BLANCO}         ******************************\n"
 }
 
 # Comprobar conexion by geminis_demon
 f_comprobarConexion() {
    if [ ! "$(ping google.com -c1 2>/dev/null)" ]; then
-      echo "No tengo internet ... el script se cerrara."
-      echo ""
+      echo -e "${BLANCO}No tengo internet ... el script se cerrara.${RESET}\n"
       exit 1
    fi
 }
@@ -71,19 +57,16 @@ f_comprobarUpdates() {
    DIRECTORIO=$(find /opt/wifislax-updaters -type f -name ${PRGNAM}_updater| rev | cut -d/ -f2- | rev)
    SERVIDOR_VERSION=$(timeout -s SIGTERM 10 curl -sk $SERVIDOR_WEB/${DIRECTORIO##*/}/${PRGNAM}_updater | grep "SCRIPT_VERSION=" | head -1 |cut -d "=" -f2)
 
-   echo ${CYAN}Version Script$CIERRE: $ROJO${SCRIPT_VERSION:6}$BLANCO/$AMARILLO${SCRIPT_VERSION:4:2}$BLANCO/$ROJO${SCRIPT_VERSION:0:4}$CIERRE
+   echo -e "${CYAN}Version Script${RESET}: ${ROJO}${SCRIPT_VERSION:6}${BLANCO}/${AMARILLO}${SCRIPT_VERSION:4:2}${BLANCO}/${ROJO}${SCRIPT_VERSION:0:4}${RESET}\n"
 
    if [ "$(ping github.com -c1 2>/dev/null)" ]; then
       if [[ $SCRIPT_VERSION -lt $SERVIDOR_VERSION ]]; then
-         echo
-         echo "$ROSA"Comprobando si hay actualizaciones para el script..."$CIERRE."
-         echo ${ROJO}NUEVA VERSION$CIERRE
-         echo
-         echo ${ROSA}Version Server$CIERRE: $ROJO${SERVIDOR_VERSION:6}$BLANCO/$AMARILLO${SERVIDOR_VERSION:4:2}$BLANCO/$ROJO${SERVIDOR_VERSION:0:4}$CIERRE
-         echo
-         echo ${CYAN}Actualizando ${PRGNAM}_updater
+         echo -e "${ROSA}"Comprobando si hay actualizaciones para el script..."${RESET}.\n"
+         echo -e "${ROJO}NUEVA VERSION${RESET}\n"
+         echo -e "${ROSA}Version Server${RESET}: ${ROJO}${SERVIDOR_VERSION:6}${BLANCO}/${AMARILLO}${SERVIDOR_VERSION:4:2}${BLANCO}/${ROJO}${SERVIDOR_VERSION:0:4}${RESET}\n"
+         echo -e "${CYAN}Actualizando ${PRGNAM}_updater"
          curl -sk $SERVIDOR_WEB/${DIRECTORIO##*/}/${PRGNAM}_updater -o $DIRECTORIO/${PRGNAM}_updater
-         echo ${ROJO}LISTO$CIERRE
+         echo -e "${ROJO}LISTO${RESET}\n"
          $0
          exit
       fi
@@ -125,22 +108,16 @@ f_versionInstalada() {
    else
    VERSIONLOCAL=$PRGNAM-$INSTALADA
    fi
-   echo ""
-   echo ""$AMARILLO"La version del sistema es..."$CYAN"$VERSIONLOCAL"$CIERRE""
-   echo ""
-   echo "__________________________________________"
-   echo ""
-   echo ""$AMARILLO"La version mas nueva en su pagina web es..."$CYAN"$PRGNAM-$VERSION"$CIERRE""
-   echo ""
+   echo -e "${AMARILLO}"La version del sistema es..."${CYAN}"$VERSIONLOCAL"${RESET}\n"
+   echo -e "__________________________________________\n"
+   echo -e "${AMARILLO}"La version mas nueva en su pagina web es..."${CYAN}"$PRGNAM-$VERSION"${RESET}\n"
    if [ $PRGNAM = x265 ]; then
-      echo "${ROJO}ADVERTENCIA:"
-      echo "${BLANCO}Actualizar este paquete puede romper ${AMARILLO}ffmpeg"
-      echo "${BLANCO}Es posible que necesites recompilar ${AMARILLO}ffmpeg"
-      echo
+      echo -e "${ROJO}ADVERTENCIA:"
+      echo -e "${BLANCO}Actualizar este paquete puede romper ${AMARILLO}ffmpeg"
+      echo -e "${BLANCO}Es posible que necesites recompilar ${AMARILLO}ffmpeg\n"
    fi
-   echo ""$BLANCO"Pulsa $ROJO"ENTER" $BLANCO"si deseas actualizarla""
+   echo -e "${BLANCO}Pulsa ${ROJO}ENTER ${BLANCO}si deseas actualizarla ${RESET}\n"
    read junk
-   echo ""
 
 # Si el paquete esta instalado y es el mismo se sube el numero de build
 if [ "$INSTALADA" = $VERSION ]; then
@@ -153,20 +130,17 @@ COMIENZO=$(date +%s)
 }
 
 f_dependencias(){
-echo "$ROSA"Comprobando dependencias ..."$CIERRE"
-echo ""
+echo -e "${ROSA}Comprobando dependencias ...${RESET}\n"
 for D in $DEPENDENCIAS; do
 BUSCAR=$(echo "$(ls /var/lib/pkgtools/packages|rev|cut -d '-' -f4-|rev|grep -x $D)")
 if [ -z "$BUSCAR" ]; then
-echo "${BLANCO}Dependencia ${AMARILLO}${D} ${ROJO}NO INSTALADA${BLANCO} ...resolviendo${CIERRE}."
+echo -e "${BLANCO}Dependencia ${AMARILLO}${D} ${ROJO}NO INSTALADA${BLANCO} ...resolviendo. ${RESET}\n"
 UPDATER=$(echo "$(find /opt/wifislax-updaters/* -name ${D}_updater)")
 if [ -z "$UPDATER" ]; then
 if [ "$(ping www.slackbuilds.org -c1 2>/dev/null)" ]; then
 slapt-src -u &>/dev/null
 else
-echo ${ROJO}
-echo "Parece que slackbuilds.org no responde ... intentalo mas tarde"
-echo ${CIERRE}
+echo -e "${ROJO}Parece que slackbuilds.org no responde ... intentalo mas tarde ${RESET}\n"
 exit 1
 fi
 if [ ${D} = pylast ]; then
@@ -184,9 +158,7 @@ fi
 fi
 VERIFICAR=$(echo "$(ls /var/lib/pkgtools/packages|rev|cut -d '-' -f4-|rev|grep -x $D)")
 if [ -z "$VERIFICAR" ]; then
-echo ""
-echo "${ROJO}No se puedo resolver la dependencia ${AMARILLO}${D}${CIERRE}."
-echo ""
+echo -e "${ROJO}No se puedo resolver la dependencia ${AMARILLO}${D}${BLANCO}.${RESET}\n"
 exit 1
 else
 if [ "${PACKAGETYPE}" = txz ]; then
@@ -195,7 +167,7 @@ fi
 if [ "${PACKAGETYPE}" = xzm ]; then
 xterm -e sh -c "txz2xzm "${PACKDIR}" "${HOME}/$ESCRITORIO/${PRGNAM}_depends/$GROUP/$XZMPACK""
 fi
-echo "${BLANCO}Dependencia ${AMARILLO}${D} ${CYAN}RESUELTA${CIERRE}."
+echo -e "${BLANCO}Dependencia ${AMARILLO}${D} ${CYAN}RESUELTA${BLANCO}.${RESET}\n"
 fi
 rm -rf /usr/src/slapt-src/${GROUP}/${D}
 find /usr/src/slapt-src -empty -type d -delete
@@ -203,16 +175,14 @@ else
 xterm -e sh -c "yes y | $UPDATER"
 VERIFICAR=`echo "$(ls /var/lib/pkgtools/packages|rev|cut -d '-' -f4-|rev|grep -x $D)"`
 if [ -z "$VERIFICAR" ]; then
-echo ""
-echo "${ROJO}No se puedo resolver la dependencia ${AMARILLO}${D}${CIERRE}."
-echo ""
+echo -e "${ROJO}No se puedo resolver la dependencia ${AMARILLO}${D}${BLANCO}.${RESET}\n"
 exit 1
 else
-echo "${BLANCO}Dependencia ${AMARILLO}${D} ${CYAN}RESUELTA${CIERRE}."
+echo -e "${BLANCO}Dependencia ${AMARILLO}${D} ${CYAN}RESUELTA${BLANCO}.${RESET}\n"
 fi
 fi
 else
-echo "${BLANCO}Dependencia ${AMARILLO}${D} ${VERDE}INSTALADA${CIERRE}."
+echo -e "${BLANCO}Dependencia ${AMARILLO}${D} ${VERDE}INSTALADA${BLANCO}.${RESET}\n"
 fi
 done
 }
@@ -224,9 +194,7 @@ f_elimina() {
    /opt/lampp/lampp stop &>/dev/null
    fi
    fi
-
-   echo ""
-   echo "$ROJO"Eliminando la version del sistema..."$CIERRE"
+   echo -e "${ROJO}Eliminando la version del sistema... ${RESET}\n"
    removepkg $(ls /var/lib/pkgtools/packages|rev|cut -d'-' -f3-|sed 's/-/ /'|rev|grep "^$PRGNAM "|cut -d' ' -f1)
 }
 
@@ -260,19 +228,15 @@ ARGS=clone
 fi
 
 if [ ! -f $SOURCES ]; then
-echo 
-echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
-echo "${ROSA}"
+echo -e "${CYAN}Descargando sources de $PRGNAM-$VERSION ${ROSA}\n"
 $GESTOR $ARGS $DOWNLOAD
-echo "${CIERRE}"
 fi
+echo -e $RESET
 }
 
 #Preparamos entorno
 f_descomprimir(){
-	echo
-	echo "$VERDE"Descomprimiendo ..."$CIERRE"
-	echo
+	echo -e "${VERDE}Descomprimiendo ...${RESET}\n"
 	sleep 1
 	rm -rf $PRGNAM-$VERSION
 	if [ $EXTENSION = zip ]; then
@@ -284,11 +248,9 @@ f_descomprimir(){
 
 f_cd(){
 	if [ -z $CD ]; then
-	echo
-	echo "${ROJO}La funcion CD no existe o esta vacia.${CIERRE}"
-	echo
+	echo -e "${ROJO}La funcion CD no existe o esta vacia. ${RESET}\n"
 	fi
-	cd $TMP/$CD||echo "${ROJO}Error en funcion CD.${CIERRE}"
+	cd $TMP/$CD||echo -e "${ROJO}Error en funcion CD. ${RESET}\n"
 	chown -R root:root .
 	find -L . \
 	\( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
@@ -309,8 +271,7 @@ f_categoria(){
 f_xzm(){
    ### Package xzm ###
    if [ $PACKAGETYPE = xzm ]; then
-   echo ""
-   echo "$VERDE"Instalando y creando modulo ${AMARILLO}xzm ..."$CIERRE"
+   echo -e "\n${VERDE}Instalando y creando modulo ${AMARILLO}xzm ...${RESET}\n"
    sleep 1
 
    f_categoria
@@ -325,8 +286,7 @@ f_xzm(){
 f_txz(){
    ### Package txz ###
    if [ $PACKAGETYPE = txz ]; then
-   echo ""
-   echo "$VERDE"Instalando y creando paquete ${AMARILLO}txz ..."$CIERRE"
+   echo -e "\n${VERDE}Instalando y creando paquete ${AMARILLO}txz ...${RESET}\n"
    sleep 1
    
    f_categoria
@@ -356,8 +316,7 @@ f_txz(){
 f_disable(){
    ### Package disabled ###
    if [ $PACKAGETYPE = disable ]; then
-   echo ""
-   echo "$VERDE"Instalando ..."$CIERRE"
+   echo -e "${VERDE}"Instalando ..."${RESET}\n"
    sleep 1
    
    #Creamos paquete
@@ -390,7 +349,7 @@ f_tareasFinales() {
    clear
    
    # Actualizar sistema mimetypes schemas etc
-   echo ""$VERDE"Actualizando sistema$BLANCO...$CIERRE"
+   echo -e "${VERDE}Actualizando sistema${BLANCO}...${RESET}\n"
 
    # Comandos de sistema
    cacheupdater
@@ -403,21 +362,16 @@ f_tareasFinales() {
    # Informe final
    clear
    if [ $PACKAGETYPE = disable ]; then
-   echo ""$VERDE"Instalado paquete "$AMARILLO"$PRGNAM-$VERSION"$CIERRE""
-   echo ""
+   echo -e "\n${VERDE}Instalado paquete${AMARILLO} $PRGNAM-$VERSION ${RESET}|n"
    else
-   echo ""$VERDE"Instalado y Creado paquete "$AMARILLO"$PRGNAM-$VERSION"$CIERRE""
-   echo ""
+   echo -e "\n${VERDE}Instalado y Creado paquete${AMARILLO} $PRGNAM-$VERSION ${RESET}\n"
    fi
    # Variables para calcular tiempo de acabado
    AHORA=$(($(date +%s)-3600));
    TIEMPO="$(date --date=@$(($AHORA-$COMIENZO)) +%X)"
    
    # Informe de acabado
-   echo "${AMARILLO}Tiempo empleado${BLANCO}: $TIEMPO"
-   echo ""
-   echo "$VERDE"Bye Bye"$CIERRE"
-   echo ""
+   echo -e "${AMARILLO}Tiempo empleado${BLANCO}: $TIEMPO ${RESET}\n\n${VERDE}Bye Bye${RESET}\n"
    
    # Salimos del script
    exit 0
