Mejorados openshot y lives

diff --git a/Multimedia/lives_updater b/Multimedia/lives_updater
--- a/Multimedia/lives_updater
+++ b/Multimedia/lives_updater
@@ -2,7 +2,7 @@
 
 # Script by www.seguridadwireless.net
 
-SCRIPT_VERSION=20160529
+SCRIPT_VERSION=20161103
 CATEGORIA="Editores de video"
 
 ############################################################
@@ -18,8 +18,7 @@ f_variables(){
 # Definicion de variables
 F_variables() {
 	WEB=http://lives-video.com/index.php?do=downloads
-	#VERSION=`curl -s $WEB|grep -a .tar.bz2|cut -d - -f3|cut -d t -f-1|sed "s/.$//g"`
-	VERSION=2.6.2
+	VERSION=`curl -s $WEB|grep -a .tar.bz2|cut -d - -f3|cut -d t -f-1|sed "s/.$//g"`
 	PRGNAM=lives
 	SRCNAM=LiVES
 	echo -ne "\033]2;${PRGNAM}_updater\007"
@@ -30,7 +29,7 @@ F_variables() {
 
 # Comprobar dependencias
 F_dependencias(){
-DEPENDENCIAS="ffmpeg"
+DEPENDENCIAS="ffmpeg mjpegtools ladspa_sdk libunicap libdv schroedinger frei0r libavc1394"
 f_dependencias
 }
 
@@ -40,6 +39,11 @@ echo
 echo "$VERDE"Compilando ..."$CIERRE"
 sleep 2
 
+# Don't build toonz plugin (build failure when opencv is present)
+# https://sourceforge.net/p/lives/bugs/217/
+sed -i -e '/toonz/d' lives-plugins/weed-plugins/Makefile.am
+automake
+
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
 ./configure \
@@ -48,11 +52,11 @@ CXXFLAGS="$SLKCFLAGS" \
   --sysconfdir=/etc \
   --localstatedir=/var \
   --mandir=/usr/man \
-  --build=$ARCH-slackware-linux \
+  --docdir=/usr/doc/$PRGNAM-$VERSION \
+  --build=$ARCH-slackware-linux
 
-make  || exit 1
-mkdir -p $PKG/usr/bin
-make install DESTDIR=$PKG
+make || exit 1
+make install-strip DESTDIR=$PKG
 
 cd $PKG/usr/bin && rm -f lives && ln -s lives-exe lives
 }
